In [5]:
# K-Means clustering with a 2D array data
# import modules
import numpy as np
from scipy.cluster.vq import whiten, kmeans, vq, kmeans2


In [6]:
# observations
data = np.array([[1, 3, 4, 5, 2],
				[2, 3, 1, 6, 3],
				[1, 5, 2, 3, 1],
				[3, 4, 9, 2, 1]])

# normalize
data = whiten(data)

print(data)


[[1.20604538 3.61813613 1.29777137 3.16227766 2.41209076]
 [2.41209076 3.61813613 0.32444284 3.79473319 3.61813613]
 [1.20604538 6.03022689 0.64888568 1.8973666  1.20604538]
 [3.61813613 4.82418151 2.91998558 1.26491106 1.20604538]]


In [7]:
# code book generation
centroids, mean_value = kmeans(data, 3)

print("Code book :\n", centroids, "\n")
print("Mean of Euclidean distances :",
	mean_value.round(4))


Code book :
 [[1.80906807 3.61813613 0.81110711 3.47850543 3.01511345]
 [3.61813613 4.82418151 2.91998558 1.26491106 1.20604538]
 [1.20604538 6.03022689 0.64888568 1.8973666  1.20604538]] 

Mean of Euclidean distances : 0.5158


In [8]:
# mapping the centroids
clusters, distances = vq(data, centroids)

print("Cluster index :", clusters, "\n")
print("Distance from the centroids :", distances)


Cluster index : [0 0 2 1] 

Distance from the centroids : [1.03155942 1.03155942 0.         0.        ]


In [9]:
# assign centroids and clusters
centroids, clusters = kmeans2(data, 3,
							minit='random')

print("Centroids :\n", centroids, "\n")
print("Clusters :", clusters)


Centroids :
 [[ 1.80906807  3.61813613  0.81110711  3.47850543  3.01511345]
 [ 2.41209076  5.4272042   1.78443563  1.58113883  1.20604538]
 [ 2.1732269   4.54423621 -1.00513381  4.01113924  3.90224353]] 

Clusters : [0 0 1 1]


C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scipy\cluster\vq.py:602: UserWarning: One of the clusters is empty. Re-run kmeans with a different initialization.
  warnings.warn("One of the clusters is empty. "


In [12]:
# K-Means clustering of Diabetes dataset
# import modules
import matplotlib.pyplot as plt
import numpy as np
from scipy.cluster.vq import whiten, kmeans, vq
import pandas as pd

# load the dataset
dataset = pd.read_csv("diabities-train.csv",
					delimiter=",")

# excluding the outcome column
dataset = dataset[:, 0:8]

print("Data :\n", dataset, "\n")

# normalize
dataset = whiten(dataset)

# generate code book
centroids, mean_dist = kmeans(dataset, 2)
print("Code-book :\n", centroids, "\n")

clusters, dist = vq(dataset, centroids)
print("Clusters :\n", clusters, "\n")

# count non-diabetic patients
non_diab = list(clusters).count(0)

# count diabetic patients
diab = list(clusters).count(1)

# depict illustration
x_axis = []
x_axis.append(diab)
x_axis.append(non_diab)

colors = ['green', 'orange']

print("No.of.diabetic patients : " + str(x_axis[0]) +
	"\nNo.of.non-diabetic patients : " + str(x_axis[1]))

y = ['diabetic', 'non-diabetic']

plt.pie(x_axis, labels=y, colors=colors, shadow='true')
plt.show()


InvalidIndexError: (slice(None, None, None), slice(0, 8, None))